name = "lab3"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Vitaliy Kulchytskyy"]
maintainers = ["Vitaliy Kulchytskyy <vitamin6754@gmail.com>"]
maintainers-logins = ["karlenko"]

executables = ["lab3"]
[[depends-on]]
parse_args = "~0.9.0"
